services:

  backend:
    container_name: extractly-backend
    build: ./backend
    ports:
      - 8000:8000
    volumes:
      - ./backend:/app
    # command: uvicorn main:app --reload --host 0.0.0.0 --port 8000
    env_file:
      - ./backend/.env

  frontend:
    container_name: extractly-frontend
    build: ./frontend
    environment:
      - API_BASE_URL=http://backend:8000
    volumes:
      - './frontend:/app'
    ports:
      - 8080:80
